---

services:
  app:
    container_name: zvezde-granda-downloader
    # image: subasically/zvezde-granda-downloader:latest # Disable for local development
    build: .
    volumes:
      - /home/subasically/repo/zvezde-granda-downloader/downloads:/usr/src/app/downloads
    environment:
      - API_KEY=${YOUR_YOUTUBE_API_KEY}
      - CHANNEL_ID=${DESIRED_YOUTUBE_CHANNEL_ID}
      - SLACK_WEBHOOK=${SLACK_WEBHOOK_URL}
    restart: always
